export const STOCKS = {
    LOAD_SUCCESS: "STOCK/LOAD_SUCC",
    LOAD_START: "STOCK/LOAD_START",
    PAGE_SIZE: "STOCKS/PAGE_SIZE",
    INDIVIDUAL_LOAD_START: "STOCK/IND_LOAD_START",
    INDIVIDUAL_LOAD_SUCCESS: "STOCK/IND_LOAD_SUCCESS",
    SEARCH: "STOCK_SEARCH",
};